In [61]:
import pandas as pd
import os

In [62]:
work_dir = os.getcwd().removesuffix("/data_management")
work_dir

'/Users/lucabellani/Documents/UNI/Tesi/Recommersion'

In [63]:
data_dir = work_dir+"/data/SpotigemDB"
data_dir

'/Users/lucabellani/Documents/UNI/Tesi/Recommersion/data/SpotigemDB'

In [64]:
artist = pd.read_csv(data_dir+"/artists_202404241006.csv", sep='\t', on_bad_lines="skip").dropna()
join = pd.read_csv(data_dir+"/join_artists_tracks_202404241007.csv", sep='\t').dropna()
tracks = pd.read_csv(data_dir+"/tracks_202404240955.csv", sep='\t', on_bad_lines="skip").dropna()

print(artist.columns)
print(join.columns)
print(tracks.columns)

Index(['id', 'followers', 'genres', 'href', 'name', 'popularity', 'uri'], dtype='object')
Index(['id_artist', 'id_track'], dtype='object')
Index(['id', 'uri', 'preview', 'title', 'albumtitle', 'albumid', 'duration',
       'key', 'mode', 'timesignature', 'acousticness', 'danceability',
       'energy', 'instrumentalness', 'liveness', 'loudness', 'speechiness',
       'valence', 'tempo', 'popularity'],
      dtype='object')

In [65]:
half_join = tracks.set_index("id").join(join.set_index("id_track"))\
                  .rename(columns={"uri":"uri_track", "popularity":"popularity_track"})
full_data = half_join.set_index("id_artist").join(artist.set_index("id"))
full_data.columns

Index(['uri_track', 'preview', 'title', 'albumtitle', 'albumid', 'duration',
       'key', 'mode', 'timesignature', 'acousticness', 'danceability',
       'energy', 'instrumentalness', 'liveness', 'loudness', 'speechiness',
       'valence', 'tempo', 'popularity_track', 'followers', 'genres', 'href',
       'name', 'popularity', 'uri'],
      dtype='object')

In [66]:
columns = ['uri_track', 'preview', 'title','energy','valence', 'name']
full_data = full_data[columns]
full_data

,uri_track,preview,title,energy,valence,name
id_artist,,,,,,
7GxkHuCxqtPAVnpBTjObpn,spotify:track:0JV6KzAXxxl3AJcwc3Hthk,https://p.scdn.co/mp3-preview/f57fcd3da0d93f89...,The shadow of your smile,0.508,0.328,Bobby Solo
07CCAKyWP9GKrifd1An3ez,spotify:track:5y0XDjmKSscPmpFjRX24wa,https://p.scdn.co/mp3-preview/52b174bebd81d846...,Oggi sono tanto triste,0.700,0.470,Giuliano e i notturni
1FFNq5gqeUoccfu8G7VH6O,spotify:track:5AIh8f3cYhcpib8gCfSYnW,https://p.scdn.co/mp3-preview/dff97b626b2c8e3e...,This Rain,0.832,0.856,NaN
5dUI54FMDxPqaXbNs4kLpB,spotify:track:0azArIwW689jNYvLFusbvH,https://p.scdn.co/mp3-preview/9b76a9d49617f5b4...,Charade,0.932,0.866,Nicola Conte
237CwiTh0USBnyLOSC3FIW,spotify:track:3hZnJIJgkTl8992Rw61qAQ,https://p.scdn.co/mp3-preview/9acf94f291c4b626...,L'appuntamento,0.757,0.712,Ex-Otago
...,...,...,...,...,...,...
7CajNmpbOovFoOoasH2HaY,spotify:track:7MmG8p0F9N3C4AXdK6o6Eb,https://p.scdn.co/mp3-preview/258a571c0ae04c58...,Outside (feat. Ellie Goulding),0.823,0.418,Calvin Harris
0X2BH1fck6amBIoJhDVmmJ,spotify:track:7MmG8p0F9N3C4AXdK6o6Eb,https://p.scdn.co/mp3-preview/258a571c0ae04c58...,Outside (feat. Ellie Goulding),0.823,0.418,Ellie Goulding
7H55rcKCfwqkyDFH9wpKM6,spotify:track:4qefHyLKbyW3yeqk5Jrjey,https://p.scdn.co/mp3-preview/b80d6e2a426bd586...,A Thousand Years,0.407,0.161,Christina Perri
07YZf4WDAMNwqr4jfgOZ8y,spotify:track:6g6A7qNhTfUgOSH7ROOxTD,https://p.scdn.co/mp3-preview/1bc07a5c8add9558...,Talk Dirty (feat. 2 Chainz),0.652,0.759,Jason Derulo
17lzZA2AlOHwCwFALHttmp,spotify:track:6g6A7qNhTfUgOSH7ROOxTD,https://p.scdn.co/mp3-preview/1bc07a5c8add9558...,Talk Dirty (feat. 2 Chainz),0.652,0.759,2 Chainz

In [67]:
print(full_data.iloc[0]["preview"])

https://p.scdn.co/mp3-preview/f57fcd3da0d93f8921b027efedaee62ac7155251?cid=61a9bb7d5c7b4b0993b2a4af35e647a3

In [68]:
songs = pd.read_pickle("../data/Songs_path")
songs

,musicId,Arousal,Valence,title,artist,mp3_path
0,1,0.4000,0.575000,Good Drank,2 Chainz,/Users/lucabellani/Documents/UNI/Tesi/Recommer...
1,4,0.2625,0.287500,X Bitch (feat. Future),21 Savage,/Users/lucabellani/Documents/UNI/Tesi/Recommer...
2,5,0.1500,0.200000,No Heart,21 Savage,/Users/lucabellani/Documents/UNI/Tesi/Recommer...
3,6,0.5125,0.350000,Red Opps,21 Savage,/Users/lucabellani/Documents/UNI/Tesi/Recommer...
4,7,0.7000,0.725000,Girls Talk Boys,5 Seconds Of Summer,/Users/lucabellani/Documents/UNI/Tesi/Recommer...
...,...,...,...,...,...,...
53,3054,0.1500,0.571429,Interlude,Tom La Meche,/Users/lucabellani/Documents/UNI/Tesi/Recommer...
54,3055,0.5500,0.476190,Vide grenier,Goo Goo Cluster,/Users/lucabellani/Documents/UNI/Tesi/Recommer...
55,3056,0.4000,0.476190,happy child singing,Ruediger Kramer,/Users/lucabellani/Documents/UNI/Tesi/Recommer...
56,3057,0.9575,0.040476,Au Feu,La Verue,/Users/lucabellani/Documents/UNI/Tesi/Recommer...
57,3058,0.7000,0.190476,Inside Views,La Verue,/Users/lucabellani/Documents/UNI/Tesi/Recommer...

In [69]:
full_data.rename(columns={"uri_track":"musicId","arousal":"Arousal", "valence":"Valence",\
                    "name":"artist","preview":"mp3_path", "energy":"Arousal"} ,inplace=True)
full_data = full_data.dropna().drop_duplicates(subset=['title'], keep='last')

In [70]:
full_data

,musicId,mp3_path,title,Arousal,Valence,artist
id_artist,,,,,,
7GxkHuCxqtPAVnpBTjObpn,spotify:track:0JV6KzAXxxl3AJcwc3Hthk,https://p.scdn.co/mp3-preview/f57fcd3da0d93f89...,The shadow of your smile,0.508,0.328,Bobby Solo
07CCAKyWP9GKrifd1An3ez,spotify:track:5y0XDjmKSscPmpFjRX24wa,https://p.scdn.co/mp3-preview/52b174bebd81d846...,Oggi sono tanto triste,0.700,0.470,Giuliano e i notturni
237CwiTh0USBnyLOSC3FIW,spotify:track:3hZnJIJgkTl8992Rw61qAQ,https://p.scdn.co/mp3-preview/9acf94f291c4b626...,L'appuntamento,0.757,0.712,Ex-Otago
3pwoLiEbkKB4c4Vj9Mzypk,spotify:track:6xjiuEP8iikKIVwEXTTAf1,https://p.scdn.co/mp3-preview/ec8960fcd0983d4f...,Oh Charlie chéri,0.575,0.453,Brigitte
5N5tQ9Dx1h8Od7aRmGj7Fi,spotify:track:1wyVyr8OhYsC9l0WgPPbh8,https://p.scdn.co/mp3-preview/ca64c4c8312974f3...,Bela Lugosi's Dead (Official Version),0.692,0.552,Bauhaus
...,...,...,...,...,...,...
1rw8ZTLnDHd74TWDDukjVi,spotify:track:1I8tHoNBFTuoJAlh4hfVVE,https://p.scdn.co/mp3-preview/fdc52b388511ac85...,Firestone,0.634,0.411,Conrad Sewell
48sLioddyaXkuhyHXSkpsB,spotify:track:5masKPHeAOVNgxdLebIcK7,https://p.scdn.co/mp3-preview/a012e893a15229bf...,Stole the Show,0.635,0.475,Parson James
0X2BH1fck6amBIoJhDVmmJ,spotify:track:7MmG8p0F9N3C4AXdK6o6Eb,https://p.scdn.co/mp3-preview/258a571c0ae04c58...,Outside (feat. Ellie Goulding),0.823,0.418,Ellie Goulding
7H55rcKCfwqkyDFH9wpKM6,spotify:track:4qefHyLKbyW3yeqk5Jrjey,https://p.scdn.co/mp3-preview/b80d6e2a426bd586...,A Thousand Years,0.407,0.161,Christina Perri
17lzZA2AlOHwCwFALHttmp,spotify:track:6g6A7qNhTfUgOSH7ROOxTD,https://p.scdn.co/mp3-preview/1bc07a5c8add9558...,Talk Dirty (feat. 2 Chainz),0.652,0.759,2 Chainz

In [71]:
full = pd.concat([songs, full_data])
full

,musicId,Arousal,Valence,title,artist,mp3_path
0,1,0.4000,0.5750,Good Drank,2 Chainz,/Users/lucabellani/Documents/UNI/Tesi/Recommer...
1,4,0.2625,0.2875,X Bitch (feat. Future),21 Savage,/Users/lucabellani/Documents/UNI/Tesi/Recommer...
2,5,0.1500,0.2000,No Heart,21 Savage,/Users/lucabellani/Documents/UNI/Tesi/Recommer...
3,6,0.5125,0.3500,Red Opps,21 Savage,/Users/lucabellani/Documents/UNI/Tesi/Recommer...
4,7,0.7000,0.7250,Girls Talk Boys,5 Seconds Of Summer,/Users/lucabellani/Documents/UNI/Tesi/Recommer...
...,...,...,...,...,...,...
1rw8ZTLnDHd74TWDDukjVi,spotify:track:1I8tHoNBFTuoJAlh4hfVVE,0.6340,0.4110,Firestone,Conrad Sewell,https://p.scdn.co/mp3-preview/fdc52b388511ac85...
48sLioddyaXkuhyHXSkpsB,spotify:track:5masKPHeAOVNgxdLebIcK7,0.6350,0.4750,Stole the Show,Parson James,https://p.scdn.co/mp3-preview/a012e893a15229bf...
0X2BH1fck6amBIoJhDVmmJ,spotify:track:7MmG8p0F9N3C4AXdK6o6Eb,0.8230,0.4180,Outside (feat. Ellie Goulding),Ellie Goulding,https://p.scdn.co/mp3-preview/258a571c0ae04c58...
7H55rcKCfwqkyDFH9wpKM6,spotify:track:4qefHyLKbyW3yeqk5Jrjey,0.4070,0.1610,A Thousand Years,Christina Perri,https://p.scdn.co/mp3-preview/b80d6e2a426bd586...
17lzZA2AlOHwCwFALHttmp,spotify:track:6g6A7qNhTfUgOSH7ROOxTD,0.6520,0.7590,Talk Dirty (feat. 2 Chainz),2 Chainz,https://p.scdn.co/mp3-preview/1bc07a5c8add9558...

In [49]:
full.to_pickle("../data/SpotiGEM_songs")