In [2]:
import pandas as pd
import numpy as np 
import os
import librosa

In [11]:
DEAM_dataset = "data/DEAM"
PMEMO_dataset = "data/PMEmo2019"

In [3]:
pmemo_annotations = PMEMO_dataset + "/annotations/static_annotations.csv"
pmemo_songs = PMEMO_dataset + "/chorus"
pmemo_metadata= PMEMO_dataset + "/metadata.csv"

PMEMO_ann= pd.read_csv(pmemo_annotations, sep =",")
PMEMO_metadata = pd.read_csv(pmemo_metadata, sep =",")

In [4]:
PMEMO_ann

     musicId  Arousal(mean)  Valence(mean)
0          1         0.4000         0.5750
1          4         0.2625         0.2875
2          5         0.1500         0.2000
3          6         0.5125         0.3500
4          7         0.7000         0.7250
..       ...            ...            ...
762      993         0.8625         0.7625
763      996         0.8750         0.5625
764      997         0.7125         0.6625
765      999         0.8750         0.7750
766     1000         0.6625         0.5750

[767 rows x 3 columns]

In [5]:
mp3_df = pd.DataFrame([], columns=["musicId", "mp3_file"])

for file in os.listdir(pmemo_songs):
    data = os.path.join(pmemo_songs, file)

    audio, sr = librosa.load(data, sr = 44100)
    mp3_df = pd.concat([mp3_df, pd.DataFrame([{"musicId": file.replace(".mp3",""), "mp3_file" :audio}])])

mp3_df

   musicId                                           mp3_file
0      752  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
0      746  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
0      791  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
0      550  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
0      236  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
..     ...                                                ...
0      950  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
0      788  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
0      763  [0.0, 2.6210937e-16, 2.569645e-16, 1.2659952e-...
0      777  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
0      993  [0.0, 2.9683367e-16, 2.2974556e-16, -6.1721226...

[794 rows x 2 columns]

In [6]:
PMEMO_ann["musicId"] = PMEMO_ann["musicId"].astype(str)
PMEMO_metadata["musicId"] = PMEMO_metadata["musicId"].astype(str)
mp3_df["musicId"] = mp3_df["musicId"].astype(str)

pmemo = PMEMO_ann.join(PMEMO_metadata.set_index("musicId"), "musicId")\
                 .join(mp3_df.set_index("musicId"), "musicId")\
                 .drop(columns=["fileName","duration", "chorus_start_time", "chorus_end_time"])\
                 .rename(columns={"Valence(mean)": "Valence", "Arousal(mean)":"Arousal"})

In [7]:
pmemo

,musicId,Arousal,Valence,title,artist,album,mp3_file
0,1,0.4000,0.5750,Good Drank,2 Chainz,"Def Jam Presents: Direct Deposit, Vol. 2","[0.0, -8.106964e-16, -5.9545294e-16, 1.866628e..."
1,4,0.2625,0.2875,X Bitch (feat. Future),21 Savage,Savage Mode,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
2,5,0.1500,0.2000,No Heart,21 Savage,Savage Mode,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
3,6,0.5125,0.3500,Red Opps,21 Savage,Red Opps,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
4,7,0.7000,0.7250,Girls Talk Boys,5 Seconds Of Summer,Ghostbusters (Original Motion Picture Soundtrack),"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
...,...,...,...,...,...,...,...
762,993,0.8625,0.7625,Stay,Zedd,Stay,"[0.0, 2.9683367e-16, 2.2974556e-16, -6.1721226..."
763,996,0.8750,0.5625,Trouble,offaiah,Trouble,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
764,997,0.7125,0.6625,A Supplementary Story : You Never Walk Alone,방탄소년단,YOU NEVER WALK ALONE,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
765,999,0.8750,0.7750,Outro : Wings,방탄소년단,YOU NEVER WALK ALONE,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
766,1000,0.6625,0.5750,Spring Day,방탄소년단,YOU NEVER WALK ALONE,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."

In [8]:
pmemo.to_pickle("./data/PMEmo_useful")

In [85]:
deam_metadata_2013 = pd.read_csv("../"+DEAM_dataset+"/DEAM_metadata/metadata_2013.csv", sep =",")
deam_metadata_2014 = pd.read_csv("../"+DEAM_dataset+"/DEAM_metadata/metadata_2014.csv", sep =",")                    
deam_metadata_2015 = pd.read_csv("../"+DEAM_dataset+"/DEAM_metadata/metadata_2015.csv", sep =",")

In [86]:
deam_metadata_2013 = deam_metadata_2013.drop(columns=["start of the segment (min.sec)", "end of the segment (min.sec)", "Genre", "file_name"])\
                                       .rename(columns = {"song_id": "musicId", "Artist" : "artist", "Song title" : "title"})
deam_metadata_2013

,musicId,artist,title
0,2,The New Mystikal Troubadours\t,\tTonight A Lonely Century\t
1,3,Kevin MacLeod\t,\tDD Groove\t
2,4,Kevin MacLeod\t,\tSlow Burn\t
3,5,My Bubba & Mi\t,\tNothing Much\t
4,7,Kevin MacLeod\t,\tHustle\t
...,...,...,...
739,995,Benjamin Bret\t,\tHonte De Toi\t
740,996,Jahzzar\t,\tFireworks\t
741,997,Halloween\t,\tMonster On Campus\t
742,999,Jahzzar\t,\tSo Easy\t
743,1000,Republic Of Lights-Got You Surrounded \t,\t Single\t

In [49]:
deam_metadata_2014 = deam_metadata_2014.drop(columns = ["segment start", "segment end", "last.fm labels"])
deam_metadata_2014.columns

Index(['Id', 'Artist', 'Album', 'Track', 'Genre'], dtype='object')

In [87]:
deam_metadata_2015 = deam_metadata_2015.drop(columns=["Filename", "album", "genre", "Unnamed: 6"])\
                                       .rename(columns = {"id": "musicId", "Artist" : "artist", "Song title" : "title"})
deam_metadata_2015

,musicId,title,artist
0,2001,Old Tree,Creepoid
1,2002,Spring Day 1,Amar Lal
2,2003,Excessive Resistance to Change,Joel Helander
3,2004,Flying,Aimee Norwich
4,2005,Waterduct,Ava Luna
5,2006,Air Traffic,Clara Berry and Wooldog
6,2007,Heavy Love,Dreamers of the Ghetto
7,2008,Disturbing Wildlife,Invisible Familiars
8,2009,Definition,Joel Helander
9,2010,Yatora,Karim Douaidy
10,2011,Toynbee Suite,Lushlife
11,2012,Impressions of Saturn,Matthew Entwistle
12,2013,The Arch,Matthew Entwistle
13,2014,You Listen,Meaxic
14,2015,Bester Jungling,NYU
15,2016,Chinese Jiang Nan,Music Delta
16,2017,Funk Jazz,Music Delta
17,2018,Modal Jazz,Music Delta
18,2019,The Broken Pledge - Chicago Reel,Phoenix
19,2020,The Collier's Daughter,Phoenix
20,2021,Stay Even,Port St Willow
21,2022,Mignon (Kennst du das Land) Op.92a Mvt.1,NYU
22,2023,Spacestation,Strand of Oaks
23,2024,Captain Sky,Tabla Breakbeat Science
24,2025,Rock Steady,Tabla Breakbeat Science
25,2026,Scorpio,Tabla Breakbeat Science
26,2027,Vermont,The Districts
27,2028,Les Fleurs Du Mal,The Scarlet Brand
28,2029,Night Owl,A Classic Education
29,2030,990,In Faded Glory
30,2031,Go,No
31,2032,Song For Jade,Kryptic Mood
32,2033,Uranium,Hunt Club
33,2034,Hey! beauty,Jacques COUTURIER
34,2035,Mit dem Unibalett im Ulmer Monster tanzen,Die Partysahnen
35,2036,Feel-ipson,Feel-ipson
36,2037,Dreamworld,engeo
37,2038,rouge et blues,Fabrice Collette
38,2039,Le Blues du Fantome,FOOL DADAZ FIRE
39,2040,FUCK THE WAR,Ralph Buckley
40,2041,Little White Church,Steven Dunston
41,2042,Classical Delay,Ogg Vorbis
42,2043,Summer,Matti Paalanen
43,2044,Habanera,Manuzik
44,2045,Jazzy Mode,Behrang Shegarfkar
45,2046,O Pindo,PELdeNOZ
46,2047,La note en cage,AdHoc
47,2048,Travelling in balochistan - late night highway,Maneros productions
48,2049,Lonely Fool,Steve.e!
49,2050,Homecoming,BeatRaider
50,2051,a fleur de peau,elbrujo
51,2052,Les 3 singes,Juice lee
52,2053,Neon,ADC LEVEL
53,2054,Interlude,Tom La Meche
54,2055,Vide grenier,Goo Goo Cluster
55,2056,happy child singing,Ruediger Kramer
56,2057,Au Feu,La Verue
57,2058,Inside Views,La Verue

In [92]:
deam_ann_2000 = pd.read_csv("../"+DEAM_dataset+"/annotations/annotations averaged per song/song_level/static_annotations_averaged_songs_1_2000.csv", sep =",")
deam_ann_2058 = pd.read_csv("../"+DEAM_dataset+"/annotations/annotations averaged per song/song_level/static_annotations_averaged_songs_2000_2058.csv", sep =",")

useful_columns = ["song_id", " valence_mean", " arousal_mean"]
deam_ann_2058 = deam_ann_2058[useful_columns].rename(columns = {" valence_mean": "Valence", " arousal_mean":"Arousal"})
deam_ann_2000 = deam_ann_2000[useful_columns].rename(columns = {" valence_mean": "Valence", " arousal_mean":"Arousal"})

print(deam_ann_2000.columns)
def normalize(col, min, max):
    return (col - min)/(max - min)

normalize(deam_ann_2000["Valence"], 1, 10)
normalize(deam_ann_2000["Arousal"], 1, 10)

normalize(deam_ann_2058["Valence"], 1, 10)
normalize(deam_ann_2058["Arousal"], 1, 10)

print(deam_ann_2000)
print(deam_ann_2058)

#Togliere file dei metadati del 2014 (o escludere titolo e artista degli altri)
#Prendere MP3
#Deam unico
#pmemo + deam

Index(['song_id', 'Valence', 'Arousal'], dtype='object')
      song_id  Valence  Arousal
0           2      3.1      3.0
1           3      3.5      3.3
2           4      5.7      5.5
3           5      4.4      5.3
4           7      5.8      6.4
...       ...      ...      ...
1739     1996      3.9      5.9
1740     1997      5.3      3.9
1741     1998      6.4      6.2
1742     1999      4.6      5.4
1743     2000      5.8      6.0

[1744 rows x 3 columns]
    song_id  Valence  Arousal
0      2001     3.20     6.60
1      2002     6.40     5.20
2      2003     5.40     4.60
3      2004     5.00     4.80
4      2005     3.80     5.20
5      2006     5.00     3.20
6      2007     3.40     4.40
7      2008     5.60     3.60
8      2009     5.20     4.20
9      2010     6.00     4.80
10     2011     4.20     5.00
11     2012     3.17     5.17
12     2013     5.40     5.60
13     2014     3.00     6.60
14     2015     6.60     5.40
15     2016     7.20     5.60
16     2017     6.67     6.50
17     2018     6.50     6.33
18     2019     6.80     6.80
19     2020     6.80     5.80
20     2021     4.20     4.40
21     2022     3.80     4.40
22     2023     5.60     3.00
23     2024     6.40     4.40
24     2025     6.00     4.80
25     2026     5.60     4.00
26     2027     5.80     5.40
27     2028     3.40     6.20
28     2029     4.17     4.00
29     2030     4.20     6.20
30     2031     4.60     3.40
31     2032     5.20     4.40
32     2033     3.17     6.83
33     2034     6.20     4.60
34     2035     3.40     4.60
35     2036     3.83     4.67
36     2037     6.40     4.40
37     2038     4.00     3.80
38     2039     5.40     4.60
39     2040     3.60     7.00
40     2041     4.40     3.00
41     2042     4.80     4.60
42     2043     5.60     4.40
43     2044     6.40     5.20
44     2045     4.80     3.20
45     2046     5.50     5.17
46     2047     6.20     5.00
47     2048     6.20     3.60
48     2049     4.40     3.80
49     2050     4.40     3.60
50     2051     3.20     4.60
51     2052     3.20     5.20
52     2053     3.80     3.80
53     2054     5.40     3.60
54     2055     5.00     5.20
55     2056     5.00     4.60
56     2057     3.17     6.83
57     2058     3.80     5.80